utra6_850:  
  gazebo_ros_control:
    pid_gains:
      joint1:
        p: 0
        i: 0 
        d: 0
      joint2:
        p: 0
        i: 0
        d: 0
      joint3:
        p: 0
        i: 0 
        d: 0
      joint4:
        p: 0
        i: 0 
        d: 0
      joint5:
        p: 0
        i: 0 
        d: 0
      joint6:
        p: 0
        i: 0 
        d: 0

