#Service name: utra/enable_get
---
# response: get utra enable 
#        value (int): There are a total of 32 bits, the 0th bit represents the enable state of the first joint brake, and so on. 
#		0xFFFF means all enable 
#		0x0000 means all disable 
#		0x0001 means only the first joint is enabled

int16 ret
int16 enable