# Service name: utra/gripper_vel_set
# request: set utra gripper velocity [0-300]

# Service name: utra/gripper_acc_set
# request: set utra gripper Acceleration [0-300]

# Service name: utra/plan_sleep
# Sleep for an amount of plan time
# request: time (float): sleep time [s]

float32 data

---

# response: 
#	ret is 0: successful  -3:disconnect  other:have error

int16 ret