/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 0x1000004b generated on 2022-10-22 02:05:53.401895
/// Generated using solver transform6d
/// To compile with gcc:
///     gcc -lstdc++ ik.cpp
/// To compile without any main function as a shared object (might need -llapack):
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp
#define IKFAST_HAS_LIBRARY
#include "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_53/ikfast.h"
using namespace ikfast;

// check if the included ikfast version matches what this file was compiled with
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
IKFAST_COMPILE_ASSERT(IKFAST_VERSION == 0x1000004b);

#include <algorithm>
#include <cmath>
#include <complex>
#include <limits>
#include <vector>

#ifndef IKFAST_ASSERT
#include <iostream>
#include <sstream>
#include <stdexcept>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b)                                                                                          \
  {                                                                                                               \
    if (!(b)) {                                                                                                   \
      std::stringstream ss;                                                                                       \
      ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " << __PRETTY_FUNCTION__ << ": Assertion '" \
         << #b << "' failed";                                                                                     \
      throw std::runtime_error(ss.str());                                                                         \
    }                                                                                                             \
  }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI ((IkReal)6.28318530717959)
#define IKPI ((IkReal)3.14159265358979)
#define IKPI_2 ((IkReal)1.57079632679490)

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#ifndef isinf
#define isinf _isinf
#endif
//#ifndef isfinite
//#define isfinite _isfinite
//#endif
#endif  // _MSC_VER

// lapack routines
extern "C" {
void dgetrf_(const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
void zgetrf_(const int* m, const int* n, std::complex<double>* a, const int* lda, int* ipiv, int* info);
void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
void dgesv_(const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
void dgetrs_(const char* trans, const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b,
             const int* ldb, int* info);
void dgeev_(const char* jobvl, const char* jobvr, const int* n, double* a, const int* lda, double* wr, double* wi,
            double* vl, const int* ldvl, double* vr, const int* ldvr, double* work, const int* lwork, int* info);
}

using namespace std;  // necessary to get std math routines

#ifdef IKFAST_NAMESPACE
namespace IKFAST_NAMESPACE {
#endif

inline float IKabs(float f) { return fabsf(f); }
inline double IKabs(double f) { return fabs(f); }

inline float IKsqr(float f) { return f * f; }
inline double IKsqr(double f) { return f * f; }

inline float IKlog(float f) { return logf(f); }
inline double IKlog(double f) { return log(f); }

// allows asin and acos to exceed 1. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_SINCOS_THRESH
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
#endif

// used to check input to atan2 for degenerate cases. has to be smaller than thresholds used for branch conds and
// evaluation
#ifndef IKFAST_ATAN2_MAGTHRESH
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
#endif

// minimum distance of separate solutions
#ifndef IKFAST_SOLUTION_THRESH
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#endif

// there are checkpoints in ikfast that are evaluated to make sure they are 0. This threshold speicfies by how much they
// can deviate
#ifndef IKFAST_EVALCOND_THRESH
#define IKFAST_EVALCOND_THRESH \
  ((IkReal)0.03)  // 5D IK has some crazy degenerate cases, but can rely on jacobian refinment to make better, just need
                  // good starting point
#endif

inline float IKasin(float f) {
  IKFAST_ASSERT(f > -1 - IKFAST_SINCOS_THRESH &&
                f < 1 + IKFAST_SINCOS_THRESH);  // any more error implies something is wrong with the solver
  if (f <= -1)
    return float(-IKPI_2);
  else if (f >= 1)
    return float(IKPI_2);
  return asinf(f);
}
inline double IKasin(double f) {
  IKFAST_ASSERT(f > -1 - IKFAST_SINCOS_THRESH &&
                f < 1 + IKFAST_SINCOS_THRESH);  // any more error implies something is wrong with the solver
  if (f <= -1)
    return -IKPI_2;
  else if (f >= 1)
    return IKPI_2;
  return asin(f);
}

// return positive value in [0,y)
inline float IKfmod(float x, float y) {
  while (x < 0) {
    x += y;
  }
  return fmodf(x, y);
}

// return positive value in [0,y)
inline double IKfmod(double x, double y) {
  while (x < 0) {
    x += y;
  }
  return fmod(x, y);
}

inline float IKacos(float f) {
  IKFAST_ASSERT(f > -1 - IKFAST_SINCOS_THRESH &&
                f < 1 + IKFAST_SINCOS_THRESH);  // any more error implies something is wrong with the solver
  if (f <= -1)
    return float(IKPI);
  else if (f >= 1)
    return float(0);
  return acosf(f);
}
inline double IKacos(double f) {
  IKFAST_ASSERT(f > -1 - IKFAST_SINCOS_THRESH &&
                f < 1 + IKFAST_SINCOS_THRESH);  // any more error implies something is wrong with the solver
  if (f <= -1)
    return IKPI;
  else if (f >= 1)
    return 0;
  return acos(f);
}
inline float IKsin(float f) { return sinf(f); }
inline double IKsin(double f) { return sin(f); }
inline float IKcos(float f) { return cosf(f); }
inline double IKcos(double f) { return cos(f); }
inline float IKtan(float f) { return tanf(f); }
inline double IKtan(double f) { return tan(f); }
inline float IKsqrt(float f) {
  if (f <= 0.0f) return 0.0f;
  return sqrtf(f);
}
inline double IKsqrt(double f) {
  if (f <= 0.0) return 0.0;
  return sqrt(f);
}
inline float IKatan2Simple(float fy, float fx) { return atan2f(fy, fx); }
inline float IKatan2(float fy, float fx) {
  if (isnan(fy)) {
    IKFAST_ASSERT(!isnan(fx));  // if both are nan, probably wrong value will be returned
    return float(IKPI_2);
  } else if (isnan(fx)) {
    return 0;
  }
  return atan2f(fy, fx);
}
inline double IKatan2Simple(double fy, double fx) { return atan2(fy, fx); }
inline double IKatan2(double fy, double fx) {
  if (isnan(fy)) {
    IKFAST_ASSERT(!isnan(fx));  // if both are nan, probably wrong value will be returned
    return IKPI_2;
  } else if (isnan(fx)) {
    return 0;
  }
  return atan2(fy, fx);
}

template <typename T>
struct CheckValue {
  T value;
  bool valid;
};

template <typename T>
inline CheckValue<T> IKatan2WithCheck(T fy, T fx, T epsilon) {
  CheckValue<T> ret;
  ret.valid = false;
  ret.value = 0;
  if (!isnan(fy) && !isnan(fx)) {
    if (IKabs(fy) >= IKFAST_ATAN2_MAGTHRESH || IKabs(fx) > IKFAST_ATAN2_MAGTHRESH) {
      ret.value = IKatan2Simple(fy, fx);
      ret.valid = true;
    }
  }
  return ret;
}

inline float IKsign(float f) {
  if (f > 0) {
    return float(1);
  } else if (f < 0) {
    return float(-1);
  }
  return 0;
}

inline double IKsign(double f) {
  if (f > 0) {
    return 1.0;
  } else if (f < 0) {
    return -1.0;
  }
  return 0;
}

template <typename T>
inline CheckValue<T> IKPowWithIntegerCheck(T f, int n) {
  CheckValue<T> ret;
  ret.valid = true;
  if (n == 0) {
    ret.value = 1.0;
    return ret;
  } else if (n == 1) {
    ret.value = f;
    return ret;
  } else if (n < 0) {
    if (f == 0) {
      ret.valid = false;
      ret.value = (T)1.0e30;
      return ret;
    }
    if (n == -1) {
      ret.value = T(1.0) / f;
      return ret;
    }
  }

  int num = n > 0 ? n : -n;
  if (num == 2) {
    ret.value = f * f;
  } else if (num == 3) {
    ret.value = f * f * f;
  } else {
    ret.value = 1.0;
    while (num > 0) {
      if (num & 1) {
        ret.value *= f;
      }
      num >>= 1;
      f *= f;
    }
  }

  if (n < 0) {
    ret.value = T(1.0) / ret.value;
  }
  return ret;
}

template <typename T>
struct ComplexLess {
  bool operator()(const complex<T>& lhs, const complex<T>& rhs) const {
    if (real(lhs) < real(rhs)) {
      return true;
    }
    if (real(lhs) > real(rhs)) {
      return false;
    }
    return imag(lhs) < imag(rhs);
  }
};

/// solves the forward kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void ComputeFk(const IkReal* j, IkReal* eetrans, IkReal* eerot) {
  IkReal x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23,
      x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46;
  x0 = IKcos(j[0]);
  x1 = IKcos(j[1]);
  x2 = IKcos(j[2]);
  x3 = IKsin(j[1]);
  x4 = IKsin(j[2]);
  x5 = IKsin(j[3]);
  x6 = IKcos(j[3]);
  x7 = IKcos(j[5]);
  x8 = IKsin(j[5]);
  x9 = IKcos(j[4]);
  x10 = IKsin(j[4]);
  x11 = IKsin(j[0]);
  x12 = ((0.0665) * x6);
  x13 = ((1.0) * x10);
  x14 = ((1.0) * x9);
  x15 = ((0.3895) * x3);
  x16 = ((1.0) * x11);
  x17 = ((0.0965) * x0);
  x18 = ((0.0965) * x11);
  x19 = ((1.0) * x0);
  x20 = ((0.364) * x11);
  x21 = ((0.0665) * x5);
  x22 = (x11 * x9);
  x23 = (x3 * x4);
  x24 = (x1 * x2);
  x25 = (x2 * x3);
  x26 = (x1 * x4);
  x27 = (x11 * x13);
  x28 = ((1.0) * x26);
  x29 = (x0 * x26);
  x30 = (x24 + x23);
  x31 = ((((-1.0) * x28)) + x25);
  x32 = (x30 * x5);
  x33 = (x31 * x6);
  x34 = ((((-1.0) * x19 * x25)) + x29);
  x35 = (x0 * ((x24 + x23)));
  x36 = ((((-1.0) * x16 * x25)) + ((x11 * x26)));
  x37 = (x11 * ((x24 + x23)));
  x38 = (x36 * x5);
  x39 = (x34 * x5);
  x40 = (x33 + x32);
  x41 = (((x30 * x6)) + ((x5 * (((((-1.0) * x25)) + x28)))));
  x42 = (((x35 * x6)) + x39);
  x43 = (x38 + ((x37 * x6)));
  IkReal x47 = ((1.0) * x19);
  x44 = (((x34 * x6)) + ((x5 * (((((-1.0) * x23 * x47)) + (((-1.0) * x24 * x47)))))));
  IkReal x48 = ((1.0) * x16);
  x45 = (((x36 * x6)) + ((x5 * (((((-1.0) * x23 * x48)) + (((-1.0) * x24 * x48)))))));
  x46 = (x43 * x9);
  eerot[0] = (((x44 * x8)) + ((x7 * (((((-1.0) * x27)) + ((x42 * x9)))))));
  eerot[1] = (((x44 * x7)) + ((x8 * (((((-1.0) * x14 * x42)) + x27)))));
  eerot[2] = (((x10 * x42)) + x22);
  IkReal x49 = ((1.0) * x17);
  eetrans[0] = ((((0.0665) * x22)) + (((0.1245) * x11)) + ((x5 * (((((-1.0) * x23 * x49)) + (((-1.0) * x24 * x49)))))) +
                (((-0.364) * x0 * x25)) + (((-1.0) * x0 * x15)) + ((x10 * ((((x21 * x34)) + ((x12 * x35)))))) +
                (((0.364) * x29)) + ((x6 * ((((x17 * x26)) + (((-1.0) * x25 * x49)))))));
  eerot[3] = (((x7 * ((((x0 * x10)) + x46)))) + ((x45 * x8)));
  eerot[4] = (((x8 * (((((-1.0) * x0 * x13)) + (((-1.0) * x14 * x43)))))) + ((x45 * x7)));
  eerot[5] = (((x10 * x43)) + (((-1.0) * x0 * x14)));
  IkReal x50 = ((1.0) * x25);
  IkReal x51 = ((1.0) * x18);
  eetrans[1] = (((x5 * (((((-1.0) * x24 * x51)) + (((-1.0) * x23 * x51)))))) + (((-0.0665) * x0 * x9)) +
                (((-0.1245) * x0)) + (((-1.0) * x11 * x15)) + ((x10 * ((((x21 * x36)) + ((x12 * x37)))))) +
                (((-1.0) * x20 * x50)) + ((x6 * ((((x18 * x26)) + (((-1.0) * x18 * x50)))))) + ((x20 * x26)));
  eerot[6] = (((x40 * x7 * x9)) + ((x41 * x8)));
  eerot[7] = (((x41 * x7)) + ((x8 * x9 * (((((-1.0) * x33)) + (((-1.0) * x32)))))));
  eerot[8] = (x10 * x40);
  eetrans[2] = ((0.0935) + ((x10 * ((((x21 * x30)) + ((x12 * x31)))))) +
                ((x5 * (((((0.0965) * x26)) + (((-0.0965) * x25)))))) + (((0.3895) * x1)) +
                ((x6 * (((((0.0965) * x23)) + (((0.0965) * x24)))))) + (((0.364) * x23)) + (((0.364) * x24)));
}

IKFAST_API int GetNumFreeParameters() { return 0; }
IKFAST_API const int* GetFreeIndices() { return NULL; }
IKFAST_API int GetNumJoints() { return 6; }

IKFAST_API int GetIkRealSize() { return sizeof(IkReal); }

IKFAST_API int GetIkType() { return 0x67000001; }

class IKSolver {
 public:
  IkReal j0, cj0, sj0, htj0, j0mul, j1, cj1, sj1, htj1, j1mul, j2, cj2, sj2, htj2, j2mul, j3, cj3, sj3, htj3, j3mul, j4,
      cj4, sj4, htj4, j4mul, j5, cj5, sj5, htj5, j5mul, new_r00, r00, rxp0_0, new_r01, r01, rxp0_1, new_r02, r02,
      rxp0_2, new_r10, r10, rxp1_0, new_r11, r11, rxp1_1, new_r12, r12, rxp1_2, new_r20, r20, rxp2_0, new_r21, r21,
      rxp2_1, new_r22, r22, rxp2_2, new_px, px, npx, new_py, py, npy, new_pz, pz, npz, pp;
  unsigned char _ij0[2], _nj0, _ij1[2], _nj1, _ij2[2], _nj2, _ij3[2], _nj3, _ij4[2], _nj4, _ij5[2], _nj5;

  IkReal j100, cj100, sj100;
  unsigned char _ij100[2], _nj100;
  bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree,
                 IkSolutionListBase<IkReal>& solutions) {
    j0 = numeric_limits<IkReal>::quiet_NaN();
    _ij0[0] = -1;
    _ij0[1] = -1;
    _nj0 = -1;
    j1 = numeric_limits<IkReal>::quiet_NaN();
    _ij1[0] = -1;
    _ij1[1] = -1;
    _nj1 = -1;
    j2 = numeric_limits<IkReal>::quiet_NaN();
    _ij2[0] = -1;
    _ij2[1] = -1;
    _nj2 = -1;
    j3 = numeric_limits<IkReal>::quiet_NaN();
    _ij3[0] = -1;
    _ij3[1] = -1;
    _nj3 = -1;
    j4 = numeric_limits<IkReal>::quiet_NaN();
    _ij4[0] = -1;
    _ij4[1] = -1;
    _nj4 = -1;
    j5 = numeric_limits<IkReal>::quiet_NaN();
    _ij5[0] = -1;
    _ij5[1] = -1;
    _nj5 = -1;
    for (int dummyiter = 0; dummyiter < 1; ++dummyiter) {
      solutions.Clear();
      r00 = eerot[0 * 3 + 0];
      r01 = eerot[0 * 3 + 1];
      r02 = eerot[0 * 3 + 2];
      r10 = eerot[1 * 3 + 0];
      r11 = eerot[1 * 3 + 1];
      r12 = eerot[1 * 3 + 2];
      r20 = eerot[2 * 3 + 0];
      r21 = eerot[2 * 3 + 1];
      r22 = eerot[2 * 3 + 2];
      px = eetrans[0];
      py = eetrans[1];
      pz = eetrans[2];

      new_r00 = r00;
      new_r01 = r01;
      new_r02 = r02;
      new_px = ((((-0.0665) * r02)) + px);
      new_r10 = r10;
      new_r11 = r11;
      new_r12 = r12;
      new_py = ((((-0.0665) * r12)) + py);
      new_r20 = r20;
      new_r21 = r21;
      new_r22 = r22;
      new_pz = ((-0.0935) + (((-0.0665) * r22)) + pz);
      r00 = new_r00;
      r01 = new_r01;
      r02 = new_r02;
      r10 = new_r10;
      r11 = new_r11;
      r12 = new_r12;
      r20 = new_r20;
      r21 = new_r21;
      r22 = new_r22;
      px = new_px;
      py = new_py;
      pz = new_pz;
      IkReal x52 = ((1.0) * px);
      IkReal x53 = ((1.0) * pz);
      IkReal x54 = ((1.0) * py);
      pp = ((px * px) + (py * py) + (pz * pz));
      npx = (((px * r00)) + ((py * r10)) + ((pz * r20)));
      npy = (((px * r01)) + ((py * r11)) + ((pz * r21)));
      npz = (((px * r02)) + ((py * r12)) + ((pz * r22)));
      rxp0_0 = ((((-1.0) * r20 * x54)) + ((pz * r10)));
      rxp0_1 = (((px * r20)) + (((-1.0) * r00 * x53)));
      rxp0_2 = ((((-1.0) * r10 * x52)) + ((py * r00)));
      rxp1_0 = ((((-1.0) * r21 * x54)) + ((pz * r11)));
      rxp1_1 = (((px * r21)) + (((-1.0) * r01 * x53)));
      rxp1_2 = ((((-1.0) * r11 * x52)) + ((py * r01)));
      rxp2_0 = (((pz * r12)) + (((-1.0) * r22 * x54)));
      rxp2_1 = (((px * r22)) + (((-1.0) * r02 * x53)));
      rxp2_2 = ((((-1.0) * r12 * x52)) + ((py * r02)));
      {
        IkReal j0eval[2];
        j0eval[0] = ((px * px) + (py * py));
        j0eval[1] = ((IKabs(px)) + (IKabs(py)));
        if (IKabs(j0eval[0]) < 0.0000010000000000 || IKabs(j0eval[1]) < 0.0000010000000000) {
          continue;  // no branches [j0]

        } else {
          {
            IkReal j0array[2], cj0array[2], sj0array[2];
            bool j0valid[2] = {false};
            _nj0 = 2;
            CheckValue<IkReal> x57 = IKatan2WithCheck(IkReal(((-1.0) * py)), IkReal(px), IKFAST_ATAN2_MAGTHRESH);
            if (!x57.valid) {
              continue;
            }
            IkReal x55 = ((1.0) * (x57.value));
            if ((((px * px) + (py * py))) < -0.00001) continue;
            CheckValue<IkReal> x58 = IKPowWithIntegerCheck(IKabs(IKsqrt(((px * px) + (py * py)))), -1);
            if (!x58.valid) {
              continue;
            }
            if ((((0.1245) * (x58.value))) < -1 - IKFAST_SINCOS_THRESH ||
                (((0.1245) * (x58.value))) > 1 + IKFAST_SINCOS_THRESH)
              continue;
            IkReal x56 = IKasin(((0.1245) * (x58.value)));
            j0array[0] = (x56 + (((-1.0) * x55)));
            sj0array[0] = IKsin(j0array[0]);
            cj0array[0] = IKcos(j0array[0]);
            j0array[1] = ((3.14159265358979) + (((-1.0) * x55)) + (((-1.0) * x56)));
            sj0array[1] = IKsin(j0array[1]);
            cj0array[1] = IKcos(j0array[1]);
            if (j0array[0] > IKPI) {
              j0array[0] -= IK2PI;
            } else if (j0array[0] < -IKPI) {
              j0array[0] += IK2PI;
            }
            j0valid[0] = true;
            if (j0array[1] > IKPI) {
              j0array[1] -= IK2PI;
            } else if (j0array[1] < -IKPI) {
              j0array[1] += IK2PI;
            }
            j0valid[1] = true;
            for (int ij0 = 0; ij0 < 2; ++ij0) {
              if (!j0valid[ij0]) {
                continue;
              }
              _ij0[0] = ij0;
              _ij0[1] = -1;
              for (int iij0 = ij0 + 1; iij0 < 2; ++iij0) {
                if (j0valid[iij0] && IKabs(cj0array[ij0] - cj0array[iij0]) < IKFAST_SOLUTION_THRESH &&
                    IKabs(sj0array[ij0] - sj0array[iij0]) < IKFAST_SOLUTION_THRESH) {
                  j0valid[iij0] = false;
                  _ij0[1] = iij0;
                  break;
                }
              }
              j0 = j0array[ij0];
              cj0 = cj0array[ij0];
              sj0 = sj0array[ij0];

              {
                IkReal j5array[2], cj5array[2], sj5array[2];
                bool j5valid[2] = {false};
                _nj5 = 2;
                IkReal x59 = cj0 * cj0;
                IkReal x60 = r01 * r01;
                IkReal x61 = r00 * r00;
                IkReal x62 = ((1.0) * sj0);
                IkReal x63 = ((4.0) * x61);
                IkReal x64 = ((8.0) * cj0 * sj0);
                IkReal x65 = ((4.0) * x60);
                IkReal x66 = ((4.0) * x59);
                CheckValue<IkReal> x71 = IKPowWithIntegerCheck(((((-1.0) * r01 * x62)) + ((cj0 * r11))), -1);
                if (!x71.valid) {
                  continue;
                }
                IkReal x67 = x71.value;
                IkReal x68 = (cj0 * r10 * x67);
                CheckValue<IkReal> x72 = IKPowWithIntegerCheck(((((-1.0) * r01 * sj0)) + ((cj0 * r11))), -1);
                if (!x72.valid) {
                  continue;
                }
                IkReal x69 = (r00 * x62 * (x72.value));
                if ((((((-1.0) * r00 * r10 * x64)) + ((x66 * (r10 * r10))) + (((-1.0) * x59 * x65)) +
                      (((-1.0) * x59 * x63)) + x63 + x65 + (((-1.0) * r01 * r11 * x64)) + ((x66 * (r11 * r11))))) <
                    -0.00001)
                  continue;
                IkReal x70 = ((0.5) * x67 *
                              (IKsqrt(((((-1.0) * r00 * r10 * x64)) + ((x66 * (r10 * r10))) + (((-1.0) * x59 * x65)) +
                                       (((-1.0) * x59 * x63)) + x63 + x65 + (((-1.0) * r01 * r11 * x64)) +
                                       ((x66 * (r11 * r11)))))));
                j5array[0] = ((2.0) * (atan((x70 + x68 + (((-1.0) * x69))))));
                sj5array[0] = IKsin(j5array[0]);
                cj5array[0] = IKcos(j5array[0]);
                j5array[1] = ((-2.0) * (atan((x70 + x69 + (((-1.0) * x68))))));
                sj5array[1] = IKsin(j5array[1]);
                cj5array[1] = IKcos(j5array[1]);
                if (j5array[0] > IKPI) {
                  j5array[0] -= IK2PI;
                } else if (j5array[0] < -IKPI) {
                  j5array[0] += IK2PI;
                }
                j5valid[0] = true;
                if (j5array[1] > IKPI) {
                  j5array[1] -= IK2PI;
                } else if (j5array[1] < -IKPI) {
                  j5array[1] += IK2PI;
                }
                j5valid[1] = true;
                for (int ij5 = 0; ij5 < 2; ++ij5) {
                  if (!j5valid[ij5]) {
                    continue;
                  }
                  _ij5[0] = ij5;
                  _ij5[1] = -1;
                  for (int iij5 = ij5 + 1; iij5 < 2; ++iij5) {
                    if (j5valid[iij5] && IKabs(cj5array[ij5] - cj5array[iij5]) < IKFAST_SOLUTION_THRESH &&
                        IKabs(sj5array[ij5] - sj5array[iij5]) < IKFAST_SOLUTION_THRESH) {
                      j5valid[iij5] = false;
                      _ij5[1] = iij5;
                      break;
                    }
                  }
                  j5 = j5array[ij5];
                  cj5 = cj5array[ij5];
                  sj5 = sj5array[ij5];
                  htj5 = IKtan(j5 / 2);

                  {
                    IkReal j2array[2], cj2array[2], sj2array[2];
                    bool j2valid[2] = {false};
                    _nj2 = 2;
                    cj2array[0] = ((-1.02411604762375) + (((3.5266402403758) * pp)) +
                                   (((-0.680641566392529) * npx * sj5)) + (((-0.680641566392529) * cj5 * npy)));
                    if (cj2array[0] >= -1 - IKFAST_SINCOS_THRESH && cj2array[0] <= 1 + IKFAST_SINCOS_THRESH) {
                      j2valid[0] = j2valid[1] = true;
                      j2array[0] = IKacos(cj2array[0]);
                      sj2array[0] = IKsin(j2array[0]);
                      cj2array[1] = cj2array[0];
                      j2array[1] = -j2array[0];
                      sj2array[1] = -sj2array[0];
                    } else if (isnan(cj2array[0])) {
                      // probably any value will work
                      j2valid[0] = true;
                      cj2array[0] = 1;
                      sj2array[0] = 0;
                      j2array[0] = 0;
                    }
                    for (int ij2 = 0; ij2 < 2; ++ij2) {
                      if (!j2valid[ij2]) {
                        continue;
                      }
                      _ij2[0] = ij2;
                      _ij2[1] = -1;
                      for (int iij2 = ij2 + 1; iij2 < 2; ++iij2) {
                        if (j2valid[iij2] && IKabs(cj2array[ij2] - cj2array[iij2]) < IKFAST_SOLUTION_THRESH &&
                            IKabs(sj2array[ij2] - sj2array[iij2]) < IKFAST_SOLUTION_THRESH) {
                          j2valid[iij2] = false;
                          _ij2[1] = iij2;
                          break;
                        }
                      }
                      j2 = j2array[ij2];
                      cj2 = cj2array[ij2];
                      sj2 = sj2array[ij2];
                      {
                        IkReal evalcond[1];
                        IkReal x73 = (sj0 * sj5);
                        IkReal x74 = ((0.150347) * px);
                        IkReal x75 = ((0.0751735) * pp);
                        IkReal x76 = (cj0 * sj5);
                        IkReal x77 = (cj5 * sj0);
                        IkReal x78 = ((0.150347) * py);
                        IkReal x79 = (cj0 * cj5);
                        evalcond[0] =
                            ((-0.028164031533375) + (((-1.0) * r10 * x75 * x76)) + (((-1.0) * r11 * x75 * x79)) +
                             ((npx * x76 * x78)) + (((-0.027500820438) * (IKcos(j2)))) + ((npy * x78 * x79)) +
                             ((r00 * x73 * x75)) + (((-1.0) * npx * x73 * x74)) + (((-1.0) * npy * x74 * x77)) +
                             ((r01 * x75 * x77)) + (((0.0969855) * pp)));
                        if (IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH) {
                          continue;
                        }
                      }

                      {
                        IkReal j3eval[2];
                        j3eval[0] = ((-1.0022931978163) + (((-1.0) * cj2)));
                        j3eval[1] = IKsign(((-219407225.0) + (((-218905232.0) * cj2))));
                        if (IKabs(j3eval[0]) < 0.0000010000000000 || IKabs(j3eval[1]) < 0.0000010000000000) {
                          continue;  // no branches [j1, j3, j4]

                        } else {
                          {
                            IkReal j3array[1], cj3array[1], sj3array[1];
                            bool j3valid[1] = {false};
                            _nj3 = 1;
                            IkReal x80 = (rxp1_0 * sj0);
                            IkReal x81 = (cj0 * rxp1_1);
                            IkReal x82 = ((1558000000.0) * pp);
                            IkReal x83 = ((300694000.0) * cj2);
                            IkReal x84 = ((281008000.0) * cj5);
                            IkReal x85 = ((300694000.0) * sj2);
                            IkReal x86 = (cj0 * rxp0_1 * sj5);
                            IkReal x87 = (cj5 * x83);
                            IkReal x88 = (cj5 * x85);
                            IkReal x89 = (rxp0_0 * sj0 * sj5);
                            CheckValue<IkReal> x90 = IKatan2WithCheck(
                                IkReal(((((-1.0) * x81 * x87)) + (((-1.0) * x81 * x84)) + (((-1.0) * sj2 * x82)) +
                                        (((-1.0) * x83 * x86)) + (((-281008000.0) * x86)) +
                                        (((441780248.0) * cj2 * sj2)) + ((x83 * x89)) + ((x80 * x84)) + ((x80 * x87)) +
                                        (((481451212.5) * sj2)) + (((281008000.0) * x89)))),
                                IkReal(((449931300.0) + (((-1.0) * x80 * x88)) + ((x81 * x88)) + ((x85 * x86)) +
                                        (((894308748.5) * cj2)) + (((441780248.0) * (cj2 * cj2))) +
                                        (((-1456000000.0) * pp)) + (((-1.0) * x85 * x89)) + (((-1.0) * cj2 * x82)))),
                                IKFAST_ATAN2_MAGTHRESH);
                            if (!x90.valid) {
                              continue;
                            }
                            CheckValue<IkReal> x91 =
                                IKPowWithIntegerCheck(IKsign(((-219407225.0) + (((-218905232.0) * cj2)))), -1);
                            if (!x91.valid) {
                              continue;
                            }
                            j3array[0] = ((-1.5707963267949) + (x90.value) + (((1.5707963267949) * (x91.value))));
                            sj3array[0] = IKsin(j3array[0]);
                            cj3array[0] = IKcos(j3array[0]);
                            if (j3array[0] > IKPI) {
                              j3array[0] -= IK2PI;
                            } else if (j3array[0] < -IKPI) {
                              j3array[0] += IK2PI;
                            }
                            j3valid[0] = true;
                            for (int ij3 = 0; ij3 < 1; ++ij3) {
                              if (!j3valid[ij3]) {
                                continue;
                              }
                              _ij3[0] = ij3;
                              _ij3[1] = -1;
                              for (int iij3 = ij3 + 1; iij3 < 1; ++iij3) {
                                if (j3valid[iij3] && IKabs(cj3array[ij3] - cj3array[iij3]) < IKFAST_SOLUTION_THRESH &&
                                    IKabs(sj3array[ij3] - sj3array[iij3]) < IKFAST_SOLUTION_THRESH) {
                                  j3valid[iij3] = false;
                                  _ij3[1] = iij3;
                                  break;
                                }
                              }
                              j3 = j3array[ij3];
                              cj3 = cj3array[ij3];
                              sj3 = sj3array[ij3];
                              {
                                IkReal evalcond[4];
                                IkReal x92 = IKcos(j3);
                                IkReal x93 = IKsin(j3);
                                IkReal x94 = (px * sj0);
                                IkReal x95 = ((1.0) * sj5);
                                IkReal x96 = (pp * sj0);
                                IkReal x97 = (cj0 * py);
                                IkReal x98 = ((1.0) * cj5);
                                IkReal x99 = (cj0 * pp);
                                IkReal x100 = (cj2 * x92);
                                IkReal x101 = ((2.0) * cj5 * npy);
                                IkReal x102 = (sj2 * x93);
                                IkReal x103 = ((2.0) * npx * sj5);
                                evalcond[0] = ((0.30901875) + (((-1.0) * pp)) + (((0.070252) * x92)) +
                                               (((0.283556) * cj2)) + (((0.0751735) * x100)) + (((0.0751735) * x102)));
                                evalcond[1] = ((0.0965) + (((0.3895) * x102)) + (((0.3895) * x100)) +
                                               (((0.364) * x92)) + (((-1.0) * npy * x98)) + (((-1.0) * npx * x95)));
                                evalcond[2] =
                                    ((((0.3895) * sj2 * x92)) + (((-0.364) * x93)) + (((-1.0) * rxp0_0 * sj0 * x95)) +
                                     ((cj0 * rxp0_1 * sj5)) + (((-0.3895) * cj2 * x93)) +
                                     (((-1.0) * rxp1_0 * sj0 * x98)) + ((cj0 * cj5 * rxp1_1)));
                                evalcond[3] =
                                    ((-0.0240285) + (((-1.0) * x103 * x97)) + (((-0.090636) * x92)) + ((x103 * x94)) +
                                     ((x101 * x94)) + (((-1.0) * r00 * x95 * x96)) + ((cj5 * r11 * x99)) +
                                     (((-1.0) * r01 * x96 * x98)) + (((-0.0969855) * x102)) + (((-0.0969855) * x100)) +
                                     (((-1.0) * x101 * x97)) + ((r10 * sj5 * x99)));
                                if (IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH ||
                                    IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH ||
                                    IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH ||
                                    IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH) {
                                  continue;
                                }
                              }

                              {
                                IkReal j1array[1], cj1array[1], sj1array[1];
                                bool j1valid[1] = {false};
                                _nj1 = 1;
                                IkReal x104 = (cj5 * sj2);
                                IkReal x105 = (cj3 * r21);
                                IkReal x106 = ((8.03212851405623) * sj3);
                                IkReal x107 = (rxp0_2 * sj5);
                                IkReal x108 = ((1.0) * cj2);
                                IkReal x109 = (cj5 * rxp1_2);
                                IkReal x110 = (r21 * sj3);
                                IkReal x111 = ((8.03212851405623) * cj3);
                                IkReal x112 = (r20 * sj3 * sj5);
                                IkReal x113 = (cj2 * x111);
                                IkReal x114 = (cj3 * r20 * sj5);
                                if (IKabs((((sj2 * x106 * x107)) + ((sj2 * x114)) + ((x109 * x113)) +
                                           (((-1.0) * x108 * x112)) + (((-1.0) * cj5 * x108 * x110)) + ((x104 * x105)) +
                                           ((rxp1_2 * x104 * x106)) + ((x107 * x113)))) < IKFAST_ATAN2_MAGTHRESH &&
                                    IKabs((((cj2 * cj5 * x105)) + (((-1.0) * rxp1_2 * x104 * x111)) + ((cj2 * x114)) +
                                           ((sj2 * x112)) + (((-1.0) * sj2 * x107 * x111)) + ((cj2 * x106 * x107)) +
                                           ((cj2 * x106 * x109)) + ((x104 * x110)))) < IKFAST_ATAN2_MAGTHRESH &&
                                    IKabs(IKsqr((((sj2 * x106 * x107)) + ((sj2 * x114)) + ((x109 * x113)) +
                                                 (((-1.0) * x108 * x112)) + (((-1.0) * cj5 * x108 * x110)) +
                                                 ((x104 * x105)) + ((rxp1_2 * x104 * x106)) + ((x107 * x113)))) +
                                          IKsqr((((cj2 * cj5 * x105)) + (((-1.0) * rxp1_2 * x104 * x111)) +
                                                 ((cj2 * x114)) + ((sj2 * x112)) + (((-1.0) * sj2 * x107 * x111)) +
                                                 ((cj2 * x106 * x107)) + ((cj2 * x106 * x109)) + ((x104 * x110)))) -
                                          1) <= IKFAST_SINCOS_THRESH)
                                  continue;
                                j1array[0] = IKatan2((((sj2 * x106 * x107)) + ((sj2 * x114)) + ((x109 * x113)) +
                                                      (((-1.0) * x108 * x112)) + (((-1.0) * cj5 * x108 * x110)) +
                                                      ((x104 * x105)) + ((rxp1_2 * x104 * x106)) + ((x107 * x113))),
                                                     (((cj2 * cj5 * x105)) + (((-1.0) * rxp1_2 * x104 * x111)) +
                                                      ((cj2 * x114)) + ((sj2 * x112)) + (((-1.0) * sj2 * x107 * x111)) +
                                                      ((cj2 * x106 * x107)) + ((cj2 * x106 * x109)) + ((x104 * x110))));
                                sj1array[0] = IKsin(j1array[0]);
                                cj1array[0] = IKcos(j1array[0]);
                                if (j1array[0] > IKPI) {
                                  j1array[0] -= IK2PI;
                                } else if (j1array[0] < -IKPI) {
                                  j1array[0] += IK2PI;
                                }
                                j1valid[0] = true;
                                for (int ij1 = 0; ij1 < 1; ++ij1) {
                                  if (!j1valid[ij1]) {
                                    continue;
                                  }
                                  _ij1[0] = ij1;
                                  _ij1[1] = -1;
                                  for (int iij1 = ij1 + 1; iij1 < 1; ++iij1) {
                                    if (j1valid[iij1] &&
                                        IKabs(cj1array[ij1] - cj1array[iij1]) < IKFAST_SOLUTION_THRESH &&
                                        IKabs(sj1array[ij1] - sj1array[iij1]) < IKFAST_SOLUTION_THRESH) {
                                      j1valid[iij1] = false;
                                      _ij1[1] = iij1;
                                      break;
                                    }
                                  }
                                  j1 = j1array[ij1];
                                  cj1 = cj1array[ij1];
                                  sj1 = sj1array[ij1];
                                  {
                                    IkReal evalcond[8];
                                    IkReal x115 = IKcos(j1);
                                    IkReal x116 = IKsin(j1);
                                    IkReal x117 = ((2.0) * pz);
                                    IkReal x118 = (cj5 * npy);
                                    IkReal x119 = ((1.0) * cj5);
                                    IkReal x120 = (cj3 * sj2);
                                    IkReal x121 = (py * sj0);
                                    IkReal x122 = ((1.0) * sj5);
                                    IkReal x123 = (cj0 * pp);
                                    IkReal x124 = (r11 * sj0);
                                    IkReal x125 = ((1.0) * cj2);
                                    IkReal x126 = (cj0 * px);
                                    IkReal x127 = (cj2 * cj3);
                                    IkReal x128 = (sj3 * x116);
                                    IkReal x129 = ((0.1245) * x115);
                                    IkReal x130 = ((2.0) * npx * sj5);
                                    IkReal x131 = (cj2 * x115);
                                    IkReal x132 = ((0.283556) * x115);
                                    IkReal x133 = ((0.070252) * x116);
                                    IkReal x134 = ((0.1245) * x116);
                                    IkReal x135 = ((0.0965) * x116);
                                    IkReal x136 = (sj2 * x115);
                                    IkReal x137 = ((0.364) * x116);
                                    IkReal x138 = (cj3 * x116);
                                    IkReal x139 = (sj3 * x136);
                                    IkReal x140 = (r10 * sj0 * x122);
                                    IkReal x141 = (x115 * x127);
                                    evalcond[0] = ((((-1.0) * r20 * x122)) + (((-1.0) * r21 * x119)) + x141 + x139 +
                                                   (((-1.0) * x125 * x128)) + ((x116 * x120)));
                                    evalcond[1] = (((x127 * x134)) + ((cj2 * sj3 * x129)) + (((-1.0) * x120 * x129)) +
                                                   (((-1.0) * rxp0_2 * x122)) + (((-1.0) * rxp1_2 * x119)) +
                                                   (((0.1245) * sj2 * x128)));
                                    evalcond[2] =
                                        ((((-1.0) * x140)) + (((-1.0) * x119 * x124)) + (((-1.0) * sj3 * x115 * x125)) +
                                         (((-1.0) * sj2 * x128)) + (((-1.0) * cj0 * r01 * x119)) +
                                         (((-1.0) * cj0 * r00 * x122)) + (((-1.0) * x125 * x138)) + ((x115 * x120)));
                                    evalcond[3] = ((((0.3895) * x115)) + (((0.0965) * x139)) +
                                                   (((-0.0965) * cj2 * x128)) + ((sj2 * x137)) + (((-1.0) * pz)) +
                                                   (((0.364) * x131)) + ((x120 * x135)) + (((0.0965) * x141)));
                                    evalcond[4] = ((((-0.1245) * cj2 * x128)) + (((-1.0) * cj0 * rxp1_0 * x119)) +
                                                   ((x120 * x134)) + (((-1.0) * cj0 * rxp0_0 * x122)) +
                                                   ((sj2 * sj3 * x129)) + (((-1.0) * rxp0_1 * sj0 * x122)) +
                                                   (((-1.0) * rxp1_1 * sj0 * x119)) + ((x127 * x129)));
                                    evalcond[5] = ((((-0.0965) * sj3 * x131)) + (((0.0965) * x115 * x120)) +
                                                   (((-1.0) * cj2 * x137)) + (((0.364) * x136)) +
                                                   (((-0.0965) * sj2 * x128)) + (((-0.3895) * x116)) +
                                                   (((-1.0) * x126)) + (((-1.0) * x121)) + (((-1.0) * x127 * x135)));
                                    evalcond[6] = ((((-1.0) * pp * r20 * x122)) + (((-0.01302625) * x139)) +
                                                   (((-1.0) * pp * r21 * x119)) + (((-1.0) * sj2 * x133)) +
                                                   (((0.02540225) * x116 * x120)) + (((-0.0751735) * x115)) +
                                                   ((npx * sj5 * x117)) + (((-1.0) * cj3 * x132)) +
                                                   (((-0.29039425) * cj2 * x128)) + (((-0.070252) * x131)) +
                                                   (((-0.27801825) * x141)) + (((-0.283556) * x128)) + ((x117 * x118)));
                                    evalcond[7] =
                                        (((x121 * x130)) + (((-1.0) * r01 * x119 * x123)) + (((-1.0) * sj3 * x132)) +
                                         ((cj2 * x133)) + (((0.02540225) * x115 * x120)) + (((0.283556) * x138)) +
                                         (((0.27801825) * x116 * x127)) + (((-1.0) * pp * x140)) +
                                         (((-0.29039425) * sj3 * x131)) + (((2.0) * x118 * x126)) +
                                         (((2.0) * x118 * x121)) + ((x126 * x130)) + (((-0.070252) * x136)) +
                                         (((-1.0) * r00 * x122 * x123)) + (((0.01302625) * sj2 * x128)) +
                                         (((0.0751735) * x116)) + (((-1.0) * pp * x119 * x124)));
                                    if (IKabs(evalcond[0]) > IKFAST_EVALCOND_THRESH ||
                                        IKabs(evalcond[1]) > IKFAST_EVALCOND_THRESH ||
                                        IKabs(evalcond[2]) > IKFAST_EVALCOND_THRESH ||
                                        IKabs(evalcond[3]) > IKFAST_EVALCOND_THRESH ||
                                        IKabs(evalcond[4]) > IKFAST_EVALCOND_THRESH ||
                                        IKabs(evalcond[5]) > IKFAST_EVALCOND_THRESH ||
                                        IKabs(evalcond[6]) > IKFAST_EVALCOND_THRESH ||
                                        IKabs(evalcond[7]) > IKFAST_EVALCOND_THRESH) {
                                      continue;
                                    }
                                  }

                                  {
                                    IkReal j4array[1], cj4array[1], sj4array[1];
                                    bool j4valid[1] = {false};
                                    _nj4 = 1;
                                    j4array[0] = 0;
                                    sj4array[0] = IKsin(j4array[0]);
                                    cj4array[0] = IKcos(j4array[0]);
                                    if (j4array[0] > IKPI) {
                                      j4array[0] -= IK2PI;
                                    } else if (j4array[0] < -IKPI) {
                                      j4array[0] += IK2PI;
                                    }
                                    j4valid[0] = true;
                                    for (int ij4 = 0; ij4 < 1; ++ij4) {
                                      if (!j4valid[ij4]) {
                                        continue;
                                      }
                                      _ij4[0] = ij4;
                                      _ij4[1] = -1;
                                      for (int iij4 = ij4 + 1; iij4 < 1; ++iij4) {
                                        if (j4valid[iij4] &&
                                            IKabs(cj4array[ij4] - cj4array[iij4]) < IKFAST_SOLUTION_THRESH &&
                                            IKabs(sj4array[ij4] - sj4array[iij4]) < IKFAST_SOLUTION_THRESH) {
                                          j4valid[iij4] = false;
                                          _ij4[1] = iij4;
                                          break;
                                        }
                                      }
                                      j4 = j4array[ij4];
                                      cj4 = cj4array[ij4];
                                      sj4 = sj4array[ij4];

                                      {
                                        std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(6);
                                        vinfos[0].jointtype = 1;
                                        vinfos[0].foffset = j0;
                                        vinfos[0].indices[0] = _ij0[0];
                                        vinfos[0].indices[1] = _ij0[1];
                                        vinfos[0].maxsolutions = _nj0;
                                        vinfos[1].jointtype = 1;
                                        vinfos[1].foffset = j1;
                                        vinfos[1].indices[0] = _ij1[0];
                                        vinfos[1].indices[1] = _ij1[1];
                                        vinfos[1].maxsolutions = _nj1;
                                        vinfos[2].jointtype = 1;
                                        vinfos[2].foffset = j2;
                                        vinfos[2].indices[0] = _ij2[0];
                                        vinfos[2].indices[1] = _ij2[1];
                                        vinfos[2].maxsolutions = _nj2;
                                        vinfos[3].jointtype = 1;
                                        vinfos[3].foffset = j3;
                                        vinfos[3].indices[0] = _ij3[0];
                                        vinfos[3].indices[1] = _ij3[1];
                                        vinfos[3].maxsolutions = _nj3;
                                        vinfos[4].jointtype = 1;
                                        vinfos[4].foffset = j4;
                                        vinfos[4].indices[0] = _ij4[0];
                                        vinfos[4].indices[1] = _ij4[1];
                                        vinfos[4].maxsolutions = _nj4;
                                        vinfos[5].jointtype = 1;
                                        vinfos[5].foffset = j5;
                                        vinfos[5].indices[0] = _ij5[0];
                                        vinfos[5].indices[1] = _ij5[1];
                                        vinfos[5].maxsolutions = _nj5;
                                        std::vector<int> vfree(0);
                                        solutions.AddSolution(vinfos, vfree);
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    return solutions.GetNumSolutions() > 0;
  }
};

/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree,
                          IkSolutionListBase<IkReal>& solutions) {
  IKSolver solver;
  return solver.ComputeIk(eetrans, eerot, pfree, solutions);
}

IKFAST_API bool ComputeIk2(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree,
                           IkSolutionListBase<IkReal>& solutions, void* pOpenRAVEManip) {
  IKSolver solver;
  return solver.ComputeIk(eetrans, eerot, pfree, solutions);
}

IKFAST_API const char* GetKinematicsHash() {
  return "<robot:GenericRobot - utra6_850 (c879581b5fd186cc61fab09b87d16813)>";
}

IKFAST_API const char* GetIkFastVersion() { return "0x1000004b"; }

#ifdef IKFAST_NAMESPACE
}  // end namespace
#endif

#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>
#ifdef IKFAST_NAMESPACE
using namespace IKFAST_NAMESPACE;
#endif

#endif
