controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_zgripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_knuckle_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: init
  - group: zgripper
    pose: close